package gui;

import dao.impl.SubmissionDao;
import domain.Assignment;
import domain.Submission;
import domain.User;
import util.FrameUtil;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.*;
import java.util.List;

public class CorrectOrCheckGUI extends JFrame {
    private JButton backButton;
    private JButton operationButton;
    private JLabel concreteScores;
    private JLabel scoresLabel;
    private JLabel submissionContentLabel;
    private JLabel cardLabel;
    private JTextArea assignmentContent;
    private JTable submissionTable;
    private JTextArea evaluationContent;
    private JLabel nullLabel;
    private JTextArea submissionContent;
    private JLabel submissionLabel;
    private JPanel evaluationPanel;
    private JPanel cardPanel;
    private JScrollPane submissionPanel;
    private JPanel mainPanel;

    SubmissionDao submissionDao = new SubmissionDao();

    CardLayout cardLayout = (CardLayout) cardPanel.getLayout();

    CardLayout evaluationLayout = (CardLayout) evaluationPanel.getLayout();

    // Click the Correct button in ManageAssignmentGUI
    public CorrectOrCheckGUI(User user, Assignment assignment) {
        setTitle("Correct an assignment");
        cardLabel.setText("Submissions:");
        cardLayout.show(cardPanel, "submissionCard");

        DefaultTableModel tableModel = new DefaultTableModel();
        submissionTable.setModel(tableModel);
        tableModel.addColumn("StudentID");
        tableModel.addColumn("Name");
        tableModel.addColumn("Time");
        tableModel.addColumn("Order");
        tableModel.addColumn("Status");
        String[] rowName = {
                "StudentID",
                "Name",
                "Time",
                "Order",
                "Status"
        };
        tableModel.addRow(rowName);

        List<Submission> submissionList = submissionDao.getSubmissionsOfOneAssignmentAndStudent(assignment.getAssignmentID(), user.getUserId());
        for (Submission submission : submissionList) {
            Object[] rowData = {
                    submission.getStudentID(),
                    user.getUsername(),
                    submission.getSubmissionTime(),
                    submission.getSubmissionOrder(),
                    submission.getSubmissionStatus()
            };
            tableModel.addRow(rowData);
        }
        TableColumn timeColumn = submissionTable.getColumnModel().getColumn(2);
        timeColumn.setCellRenderer(new SubmissionGUI.TimestampRenderer());

        operationButton.setText("Correct");

        backButton.addActionListener(e -> {
            CorrectOrCheckGUI.this.dispose();
            new ManageAssignmentGUI(user);
        });

        setContentPane(mainPanel);
        setSize(800, 500);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
        setLocationRelativeTo(null);
    }

    // Click the Check button in SubmissionGUI
    public CorrectOrCheckGUI(User user, Assignment assignment, int submissionOrder) {
        setTitle("Check out your assignment");
        cardLabel.setText(assignment.getAssignmentName());
        cardLayout.show(cardPanel, "assignmentCard");
        assignmentContent.setText(assignment.getAssignmentContent());

        Submission submission = submissionDao.getSubmissionFromTwoIDsAndOrder(assignment.getAssignmentID(), user.getUserId(), submissionOrder);
        submissionContent.setText(submission.getSubmissionContent());

        operationButton.setText("Delete");
        operationButton.addActionListener(e -> {
            if (submissionDao.deleteSubmission(submission)) {
                FrameUtil.showConfirmation(CorrectOrCheckGUI.this, "Delete successfully!");
            } else {
                FrameUtil.showConfirmation(CorrectOrCheckGUI.this, "Something wrong!");
            }
            new SubmissionGUI(user, assignment);
        });

        if (submission.getEvaluation() == null || submission.getEvaluation().isEmpty()) {
            evaluationLayout.show(evaluationPanel, "nullCard");
        } else {
            evaluationLayout.show(evaluationPanel, "evaluationCard");
            evaluationContent.setText(submission.getEvaluation());
            evaluationContent.setEditable(false);
        }

        backButton.addActionListener(e -> {
            CorrectOrCheckGUI.this.dispose();
            new SubmissionGUI(user, assignment);
        });

        setContentPane(mainPanel);
        setSize(600, 500);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
        setLocationRelativeTo(null);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JToolBar toolBar1 = new JToolBar();
        mainPanel.add(toolBar1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        backButton = new JButton();
        backButton.setText("Back");
        toolBar1.add(backButton);
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        toolBar1.add(spacer1);
        operationButton = new JButton();
        operationButton.setText("Operate");
        toolBar1.add(operationButton);
        submissionContentLabel = new JLabel();
        submissionContentLabel.setText("Evaluation:");
        mainPanel.add(submissionContentLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scoresLabel = new JLabel();
        scoresLabel.setText("Scores:");
        mainPanel.add(scoresLabel, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(25, 17), null, 0, false));
        concreteScores = new JLabel();
        concreteScores.setText("");
        mainPanel.add(concreteScores, new com.intellij.uiDesigner.core.GridConstraints(5, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(75, -1), null, 0, false));
        cardPanel = new JPanel();
        cardPanel.setLayout(new CardLayout(0, 0));
        mainPanel.add(cardPanel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(200, -1), new Dimension(250, 24), null, 0, false));
        assignmentContent = new JTextArea();
        assignmentContent.setText("");
        cardPanel.add(assignmentContent, "assignmentCard");
        submissionPanel = new JScrollPane();
        cardPanel.add(submissionPanel, "submissionCard");
        submissionTable = new JTable();
        submissionPanel.setViewportView(submissionTable);
        cardLabel = new JLabel();
        cardLabel.setText("Card content");
        mainPanel.add(cardLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        evaluationPanel = new JPanel();
        evaluationPanel.setLayout(new CardLayout(0, 0));
        mainPanel.add(evaluationPanel, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 3, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(200, -1), new Dimension(225, -1), null, 0, false));
        evaluationContent = new JTextArea();
        evaluationPanel.add(evaluationContent, "evaluationCard");
        nullLabel = new JLabel();
        nullLabel.setHorizontalAlignment(0);
        nullLabel.setHorizontalTextPosition(0);
        nullLabel.setText("No content");
        evaluationPanel.add(nullLabel, "nullCard");
        submissionContent = new JTextArea();
        mainPanel.add(submissionContent, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 50), null, 0, false));
        submissionLabel = new JLabel();
        submissionLabel.setText("Submission content:");
        mainPanel.add(submissionLabel, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
